- hosts: localhost
  vars:
    consul_cluster: dc1
    consul_cluster_addr: consul.ops.happypathway.com
    consul_config_dir: /etc/consul.d/
    consul_data_dir: /opt/consul/data
    consul_log_file: /opt/consul/logs/consul.log
    consul_home: /opt/consul
    consul_config_file: /etc/consul.d/consul-default.json
    service_port: 80
    consul_acl : false
    consul_template_config_dir: /etc/consul-template/conf.d/
    consul_template_template_dir: /etc/consul-template/templates/
    proxy_name: app.ops.happypathway.com

  tasks:
    
    - name: block for apt
      shell: while [ $(top -bn1| grep -q apt; echo $?) == '0' ]; do echo 'apt runing'; sleep 1; done

    - name: download consul agent
      get_url: url=https://releases.hashicorp.com/consul/1.0.7/consul_1.0.7_linux_amd64.zip dest=/tmp/consul_1.0.7_linux_amd64.zip

    - name: install unzip
      apt: name=unzip state=installed
      when: ansible_os_family == "Debian"
      register: result
      until: result.rc == 0
      retries: 10
      delay: 10

    - name: unzip consul
      unarchive:
        src: /tmp/consul_1.0.7_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes

    - name: create proper directories
      file: path={{ item }} state=directory mode=0755
      with_items:
        - "{{ consul_config_dir }}"
        - "{{ consul_data_dir }}"
        - "{{ consul_template_config_dir }}"
        - "{{ consul_template_template_dir }}"
    
    - name: setup config file
      template: src=consul-default.json.j2 dest={{ consul_config_file }} mode=0755 owner=root

    - name: setup service file
      template: src=service.json.j2 dest={{ consul_config_dir }}/service.json

    - name: install supervisor
      apt: name=supervisor state=installed
      register: result
      until: result.rc == 0
      retries: 10
      delay: 10
      
    - name: upload consul supervisord script
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - {"src": "consul.conf", "dest": "/etc/supervisor/conf.d/consul.conf"}

    - name: load consul with supervisord
      shell: "{{ item }}"
      with_items:
        - supervisorctl reread
        - supervisorctl update

    